apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp
  labels:  
    app: employees
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      imagePullSecrets:
      - name: ecr-secret-webapp
      containers:
      - name: webapp-container
        image: 008819936420.dkr.ecr.us-east-1.amazonaws.com/webapp-repo:v0.2
        env:
        - name: DBHOST
          value: "mysql-service.db.svc.cluster.local"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "pw"
        - name: DATABASE
          value: "employees"
        - name: DBPORT
          value: "3306"
        - name: APP_COLOR 
          value: "blue"
        ports:
        - containerPort: 8080

